[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "bash"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "bash start.sh"
